/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariablesCalidadRouteImport } from './routes/variables-calidad'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ReporteMensualRouteImport } from './routes/reporte-mensual'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as PantallasOperativasRouteImport } from './routes/pantallas-operativas'
import { Route as OperatorVisionRouteImport } from './routes/operator-vision'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ControlCalidadRouteImport } from './routes/control-calidad'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CatalogosRouteImport } from './routes/catalogos'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TFolioRouteImport } from './routes/t.$folio'
import { Route as MuestraIdRouteImport } from './routes/muestra.$id'
import { Route as HistorialMaquinaRouteImport } from './routes/historial.$maquina'
import { Route as CalidadRevisionRouteImport } from './routes/calidad.revision'
import { Route as CalidadDashboardRouteImport } from './routes/calidad.dashboard'
import { Route as CalidadCapturaFueraTurnoRouteImport } from './routes/calidad.captura-fuera-turno'
import { Route as CalidadCapturaRouteImport } from './routes/calidad.captura'
import { Route as CalidadAjustesRouteImport } from './routes/calidad.ajustes'

const VariablesCalidadRoute = VariablesCalidadRouteImport.update({
  id: '/variables-calidad',
  path: '/variables-calidad',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReporteMensualRoute = ReporteMensualRouteImport.update({
  id: '/reporte-mensual',
  path: '/reporte-mensual',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const PantallasOperativasRoute = PantallasOperativasRouteImport.update({
  id: '/pantallas-operativas',
  path: '/pantallas-operativas',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorVisionRoute = OperatorVisionRouteImport.update({
  id: '/operator-vision',
  path: '/operator-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCalidadRoute = ControlCalidadRouteImport.update({
  id: '/control-calidad',
  path: '/control-calidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogosRoute = CatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TFolioRoute = TFolioRouteImport.update({
  id: '/t/$folio',
  path: '/t/$folio',
  getParentRoute: () => rootRouteImport,
} as any)
const MuestraIdRoute = MuestraIdRouteImport.update({
  id: '/muestra/$id',
  path: '/muestra/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialMaquinaRoute = HistorialMaquinaRouteImport.update({
  id: '/historial/$maquina',
  path: '/historial/$maquina',
  getParentRoute: () => rootRouteImport,
} as any)
const CalidadRevisionRoute = CalidadRevisionRouteImport.update({
  id: '/calidad/revision',
  path: '/calidad/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const CalidadDashboardRoute = CalidadDashboardRouteImport.update({
  id: '/calidad/dashboard',
  path: '/calidad/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalidadCapturaFueraTurnoRoute =
  CalidadCapturaFueraTurnoRouteImport.update({
    id: '/calidad/captura-fuera-turno',
    path: '/calidad/captura-fuera-turno',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalidadCapturaRoute = CalidadCapturaRouteImport.update({
  id: '/calidad/captura',
  path: '/calidad/captura',
  getParentRoute: () => rootRouteImport,
} as any)
const CalidadAjustesRoute = CalidadAjustesRouteImport.update({
  id: '/calidad/ajustes',
  path: '/calidad/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/catalogos': typeof CatalogosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/control-calidad': typeof ControlCalidadRoute
  '/login': typeof LoginRoute
  '/operator-vision': typeof OperatorVisionRoute
  '/pantallas-operativas': typeof PantallasOperativasRoute
  '/produccion': typeof ProduccionRoute
  '/reporte-mensual': typeof ReporteMensualRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
  '/variables-calidad': typeof VariablesCalidadRoute
  '/calidad/ajustes': typeof CalidadAjustesRoute
  '/calidad/captura': typeof CalidadCapturaRoute
  '/calidad/captura-fuera-turno': typeof CalidadCapturaFueraTurnoRoute
  '/calidad/dashboard': typeof CalidadDashboardRoute
  '/calidad/revision': typeof CalidadRevisionRoute
  '/historial/$maquina': typeof HistorialMaquinaRoute
  '/muestra/$id': typeof MuestraIdRoute
  '/t/$folio': typeof TFolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/catalogos': typeof CatalogosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/control-calidad': typeof ControlCalidadRoute
  '/login': typeof LoginRoute
  '/operator-vision': typeof OperatorVisionRoute
  '/pantallas-operativas': typeof PantallasOperativasRoute
  '/produccion': typeof ProduccionRoute
  '/reporte-mensual': typeof ReporteMensualRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
  '/variables-calidad': typeof VariablesCalidadRoute
  '/calidad/ajustes': typeof CalidadAjustesRoute
  '/calidad/captura': typeof CalidadCapturaRoute
  '/calidad/captura-fuera-turno': typeof CalidadCapturaFueraTurnoRoute
  '/calidad/dashboard': typeof CalidadDashboardRoute
  '/calidad/revision': typeof CalidadRevisionRoute
  '/historial/$maquina': typeof HistorialMaquinaRoute
  '/muestra/$id': typeof MuestraIdRoute
  '/t/$folio': typeof TFolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/catalogos': typeof CatalogosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/control-calidad': typeof ControlCalidadRoute
  '/login': typeof LoginRoute
  '/operator-vision': typeof OperatorVisionRoute
  '/pantallas-operativas': typeof PantallasOperativasRoute
  '/produccion': typeof ProduccionRoute
  '/reporte-mensual': typeof ReporteMensualRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
  '/variables-calidad': typeof VariablesCalidadRoute
  '/calidad/ajustes': typeof CalidadAjustesRoute
  '/calidad/captura': typeof CalidadCapturaRoute
  '/calidad/captura-fuera-turno': typeof CalidadCapturaFueraTurnoRoute
  '/calidad/dashboard': typeof CalidadDashboardRoute
  '/calidad/revision': typeof CalidadRevisionRoute
  '/historial/$maquina': typeof HistorialMaquinaRoute
  '/muestra/$id': typeof MuestraIdRoute
  '/t/$folio': typeof TFolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/catalogos'
    | '/configuracion'
    | '/control-calidad'
    | '/login'
    | '/operator-vision'
    | '/pantallas-operativas'
    | '/produccion'
    | '/reporte-mensual'
    | '/reportes'
    | '/usuarios'
    | '/variables-calidad'
    | '/calidad/ajustes'
    | '/calidad/captura'
    | '/calidad/captura-fuera-turno'
    | '/calidad/dashboard'
    | '/calidad/revision'
    | '/historial/$maquina'
    | '/muestra/$id'
    | '/t/$folio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/catalogos'
    | '/configuracion'
    | '/control-calidad'
    | '/login'
    | '/operator-vision'
    | '/pantallas-operativas'
    | '/produccion'
    | '/reporte-mensual'
    | '/reportes'
    | '/usuarios'
    | '/variables-calidad'
    | '/calidad/ajustes'
    | '/calidad/captura'
    | '/calidad/captura-fuera-turno'
    | '/calidad/dashboard'
    | '/calidad/revision'
    | '/historial/$maquina'
    | '/muestra/$id'
    | '/t/$folio'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/catalogos'
    | '/configuracion'
    | '/control-calidad'
    | '/login'
    | '/operator-vision'
    | '/pantallas-operativas'
    | '/produccion'
    | '/reporte-mensual'
    | '/reportes'
    | '/usuarios'
    | '/variables-calidad'
    | '/calidad/ajustes'
    | '/calidad/captura'
    | '/calidad/captura-fuera-turno'
    | '/calidad/dashboard'
    | '/calidad/revision'
    | '/historial/$maquina'
    | '/muestra/$id'
    | '/t/$folio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CatalogosRoute: typeof CatalogosRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ControlCalidadRoute: typeof ControlCalidadRoute
  LoginRoute: typeof LoginRoute
  OperatorVisionRoute: typeof OperatorVisionRoute
  PantallasOperativasRoute: typeof PantallasOperativasRoute
  ProduccionRoute: typeof ProduccionRoute
  ReporteMensualRoute: typeof ReporteMensualRoute
  ReportesRoute: typeof ReportesRoute
  UsuariosRoute: typeof UsuariosRoute
  VariablesCalidadRoute: typeof VariablesCalidadRoute
  CalidadAjustesRoute: typeof CalidadAjustesRoute
  CalidadCapturaRoute: typeof CalidadCapturaRoute
  CalidadCapturaFueraTurnoRoute: typeof CalidadCapturaFueraTurnoRoute
  CalidadDashboardRoute: typeof CalidadDashboardRoute
  CalidadRevisionRoute: typeof CalidadRevisionRoute
  HistorialMaquinaRoute: typeof HistorialMaquinaRoute
  MuestraIdRoute: typeof MuestraIdRoute
  TFolioRoute: typeof TFolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variables-calidad': {
      id: '/variables-calidad'
      path: '/variables-calidad'
      fullPath: '/variables-calidad'
      preLoaderRoute: typeof VariablesCalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporte-mensual': {
      id: '/reporte-mensual'
      path: '/reporte-mensual'
      fullPath: '/reporte-mensual'
      preLoaderRoute: typeof ReporteMensualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantallas-operativas': {
      id: '/pantallas-operativas'
      path: '/pantallas-operativas'
      fullPath: '/pantallas-operativas'
      preLoaderRoute: typeof PantallasOperativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator-vision': {
      id: '/operator-vision'
      path: '/operator-vision'
      fullPath: '/operator-vision'
      preLoaderRoute: typeof OperatorVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-calidad': {
      id: '/control-calidad'
      path: '/control-calidad'
      fullPath: '/control-calidad'
      preLoaderRoute: typeof ControlCalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogos': {
      id: '/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof CatalogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$folio': {
      id: '/t/$folio'
      path: '/t/$folio'
      fullPath: '/t/$folio'
      preLoaderRoute: typeof TFolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muestra/$id': {
      id: '/muestra/$id'
      path: '/muestra/$id'
      fullPath: '/muestra/$id'
      preLoaderRoute: typeof MuestraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial/$maquina': {
      id: '/historial/$maquina'
      path: '/historial/$maquina'
      fullPath: '/historial/$maquina'
      preLoaderRoute: typeof HistorialMaquinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad/revision': {
      id: '/calidad/revision'
      path: '/calidad/revision'
      fullPath: '/calidad/revision'
      preLoaderRoute: typeof CalidadRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad/dashboard': {
      id: '/calidad/dashboard'
      path: '/calidad/dashboard'
      fullPath: '/calidad/dashboard'
      preLoaderRoute: typeof CalidadDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad/captura-fuera-turno': {
      id: '/calidad/captura-fuera-turno'
      path: '/calidad/captura-fuera-turno'
      fullPath: '/calidad/captura-fuera-turno'
      preLoaderRoute: typeof CalidadCapturaFueraTurnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad/captura': {
      id: '/calidad/captura'
      path: '/calidad/captura'
      fullPath: '/calidad/captura'
      preLoaderRoute: typeof CalidadCapturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad/ajustes': {
      id: '/calidad/ajustes'
      path: '/calidad/ajustes'
      fullPath: '/calidad/ajustes'
      preLoaderRoute: typeof CalidadAjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  CatalogosRoute: CatalogosRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ControlCalidadRoute: ControlCalidadRoute,
  LoginRoute: LoginRoute,
  OperatorVisionRoute: OperatorVisionRoute,
  PantallasOperativasRoute: PantallasOperativasRoute,
  ProduccionRoute: ProduccionRoute,
  ReporteMensualRoute: ReporteMensualRoute,
  ReportesRoute: ReportesRoute,
  UsuariosRoute: UsuariosRoute,
  VariablesCalidadRoute: VariablesCalidadRoute,
  CalidadAjustesRoute: CalidadAjustesRoute,
  CalidadCapturaRoute: CalidadCapturaRoute,
  CalidadCapturaFueraTurnoRoute: CalidadCapturaFueraTurnoRoute,
  CalidadDashboardRoute: CalidadDashboardRoute,
  CalidadRevisionRoute: CalidadRevisionRoute,
  HistorialMaquinaRoute: HistorialMaquinaRoute,
  MuestraIdRoute: MuestraIdRoute,
  TFolioRoute: TFolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
